version: '3'
services:
  fileserver:
    build: ./fileserver
    ports:
     - "5005:5000"
    depends_on:
      - directory
    volumes:
     - ./fileserver/:/code
  directory:
    build: ./directory
    ports:
     - "5006:5001"
    volumes:
     - ./directory/:/code 
