version: '3'
services:
  cache:
    build: ./cache
    ports:
     - "5007:5002"
    volumes:
     - ./cache/:/code 
  directory:
    build: ./directory
    ports:
     - "5006:5001"
    volumes:
     - ./directory/:/code 
  fileserver:
    build: ./fileserver
    ports:
     - "5005:5000"
    depends_on:
      - directory
    volumes:
     - ./fileserver/:/code
